brew "fzf"
brew "zoxide"
brew "ripgrep"
brew "git-delta"
brew "fish"
brew "neovim"
brew "tree-sitter-cli"
brew "jj"
brew "helix"
brew "npm"
brew "xclip" if OS.linux? # System clipboard provider for neovim (macOS uses built-in pbcopy)
brew "pyenv"
